### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Drakaris-top** [pogzyb/asyncwhois#1]
Traceback (most recent call last):
  File "C:/D/python/bulk_whois/bulk_whois.py", line 28, in <module>
    asyncio.run(main())
  File "C:\Users\Drakaris\AppData\Local\Programs\Python\Python37-32\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Drakaris\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:/D/python/bulk_whois/bulk_whois.py", line 23, in main
    await asyncio.gather(*tasks)
  File "C:\Users\Drakaris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\asyncwhois\__init__.py", line 19, in lookup
    query_result = await do_async_whois_query(domain)
  File "C:\Users\Drakaris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\asyncwhois\query.py", line 21, in do_async_whois_query
    stderr=asyncio.subprocess.PIPE
  File "C:\Users\Drakaris\AppData\Local\Programs\Python\Python37-32\lib\asyncio\subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "C:\Users\Drakaris\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1503, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "C:\Users\Drakaris\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 463, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by pogzyb** [comment]
Hi - thanks for the feedback! This exception seems to come from asyncio. Are you running the example on Windows? Looks like there are some known limitations/issues using the default loop for subprocesses on Windows.

- https://stackoverflow.com/questions/45699932/asyncio-stdout-failing
- https://docs.python.org/3/library/asyncio-platforms.html#subprocess-support-on-windows

Let me know if changing the loop type as mentioned in the links above fixes this issue. I'm not on Windows at the moment, so I can't easily test this.

**Comment by pogzyb** [comment]
@Drakaris-top Any luck?

**Comment by pogzyb** [comment]
Version 0.1.7+ no longer leverages "subprocess", so this should not be an issue moving forward.

Closing for now.
